theme: minima

title: Cesar's Blog
author: Cesar Cori
email: jcesarcori@gmail.com 
baseurl: /blog
url: https://cesarcori.github.io

description: >
  This is a blog to journey my experience in software, technology, and why not some thoughts.
