theme: minima

title: Cesar's Blog
author: Cesar Cori
email: jcesarcori@gmail.com 
url: https://cesarcori.github.io/

description: >
  This is a blog to jorney my experence in software and technology.

